In this notebook, we're going to cover some of the most fundamental concpets of tensors using Tensorflow:
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & NumPy
* Using @tf.function
* Using GPUs with tf
* Exercises


# Introduction to Tensors

## Creating tensor with tf.constant()

In [ ]:
# Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.18.0


In [ ]:
# Create a tensor with tf.constant()
scalar = tf.constant(7)
scalar

In [ ]:
# check the number of dimensions of a tensor
scalar.ndim

In [ ]:
# Create a vector
vector = tf.constant([10,10])
vector

In [ ]:
# Check the dimension of a vector
vector.ndim

In [ ]:
# Create a matrix
matrix = tf.constant([[10,7],[7,10]])
matrix

In [ ]:
matrix.ndim

In [ ]:
# Create another matriz
another_matrix = tf.constant([[10.,7.],
                              [7.,10.],
                              [8.,9.]],dtype=tf.float16) #Specify the data type

In [ ]:
another_matrix

In [ ]:
# What's the number of dimension of another_matrix
another_matrix.ndim

In [ ]:
# Let's create a tensor
tensor = tf.constant([[[1,2,3],
                      [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                     [[13,14,15],
                      [16,17,18]]])
tensor

In [ ]:
tensor.ndim

## Creating tensors with tf.variable

In [ ]:
# Create the same tensor with tf.variable() as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

In [ ]:
# Let's try change one of the elements in our changeable tensor
changeable_tensor[0] = 7

In [ ]:
changeable_tensor[0].assign(7)
changeable_tensor

In [ ]:
unchangeable_tensor[0].assign(7)

## Creating Random tensors

Randoms tensors are tensors of some arbitrary size which contain random numbers

In [ ]:
# Create two random (but the same) tensors

random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_1 = random_2.normal(shape=(3,2))



## Shuffle the order of elements in a tensor

In [ ]:
# Shuffle a tensor (valuable for when you want to shuffle your data so the inherit order does not affect learning )
not_shuffle = tf.constant([[10,7],
                           [3,4],
                           [2,5]])
# Shuffle our non-shuffle tensor
tf.random.set_seed(42)
tf.random.shuffle(not_shuffle,seed=42)

In [ ]:
tf.random.set_seed(42) #global level random seed
tf.random.shuffle(not_shuffle,seed=42) #operation level random seed

### Other ways to make tensors

In [ ]:
#Create a tensor of al ones
tf.ones([10,7])

In [ ]:
#Create a tensor of all ceros
tf.zeros([10,7])

## Turn Numpy arrays into tensors

The main difference between Numpy arrays and Tensorflow tensors is that tensors can be run on a gpu

In [ ]:
# You can also turn NumPy arryas into tensors
import numpy as np

numpy_A = np.arange(1,25,dtype=np.int32)
numpy_A

In [ ]:
A = tf.constant(numpy_A, shape=(2,3,4))
B = tf.constant(numpy_A)
A,B

## Getting more information from tensors
When dealing with tensors you probablu want to be aware of the folowing attributes
* Shape
* Rank
* Axis or dimension
* Size

In [ ]:
# Create a rank 4 tensor ( 4 dimensions)
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

In [ ]:
rank_4_tensor[0]

In [ ]:
rank_4_tensor.shape,rank_4_tensor.ndim,tf.size(rank_4_tensor)

In [ ]:
# Get various attributes of our tensor
print("datatupe of every element:", rank_4_tensor.dtype)
print("number of dimensions (rank):", rank_4_tensor.ndim)
print("shape of tensor:", rank_4_tensor.shape)
print("elements along the 0 axis:", rank_4_tensor.shape[0])
print("elements along the last axis:", rank_4_tensor.shape[-1])
print("total number of elements in our tensor:", tf.size(rank_4_tensor).numpy())


## Indexing tensor
Tensors can be indexing just like Python lists

In [ ]:
# Get the firts 2 elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

In [ ]:
# Get the first element from each dimension from each index excep for the final one
rank_4_tensor[:1,:1,:1,:]

In [ ]:
# Create a rank 2 tensor
rank_2_tensor = tf.zeros(shape=[2,2])
rank_2_tensor

In [ ]:
# Get the last item of each our rank 2 tensor
rank_2_tensor[:,-1]

In [ ]:
# Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor,axis=-1)

In [ ]:
# Expand the axis 0
tf.expand_dims(rank_2_tensor,axis=0)

## Manipulating tensors (tensor operations)
**Basic operations**

In [ ]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[10,7],[3,4]])
tensor + 10

In [ ]:
# Original tensor is unchanged
tensor

In [ ]:
# Multiplication
tensor * 100

In [ ]:
# Substraction
tensor -10

In [ ]:
# We can use the tensorflow built-in function
tf.multiply(tensor,10)

**Matrix Multiplication**

In machine learning is one of the most common tensor operations

In [ ]:
# Matrix multiplication in tensorflow
print(tensor)
tf.matmul(tensor,tensor)

In [ ]:
# Matrix multiplication with python operator "@"
tensor @ tensor

In [ ]:
# Create a tensor (3,2)
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
Y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])

In [ ]:
# Let's change the shape of Y
tf.reshape(Y,shape=(2,3))

In [ ]:
X @ tf.reshape(Y,shape=(2,3))

In [ ]:
tf.matmul(X,tf.reshape(Y,shape=(2,3)))

## Changing the datatype of the tensor

In [ ]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.7,7.4])
B.dtype

In [ ]:
C = tf.constant([7,10])
C.dtype

In [ ]:
# Change from float32 to float16 (reduced precision)
D = tf.cast(B,dtype=tf.float16)
D , D.dtype

In [ ]:
# Change from int32 to float32
E = tf.cast(C,dtype=tf.float32)
E,E.dtype

In [ ]:
E_float16 = tf.cast(E,dtype=tf.float16)
E_float16

## Aggreagation tensors

Aggregating tensor = condensing them from multiples values down to a smaller amount of values.

In [ ]:
# Get the absolute values
D = tf.constant([-7,-10])
tf.abs(D)

### Let's go through the following forms of aggregation:
* Get the min
* Get the max
* Get mean of a tensor
* Get the sum of a tensor

In [ ]:
# Create a random tensor with values between 0 and 100 of size 50
import numpy as np
E = tf.constant(np.random.randint(0,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([93, 17,  2, 77, 15, 67, 39, 42, 86, 48, 72, 27, 28, 54, 20,  8, 55,
       95, 10, 54, 82, 86, 66, 14,  0, 92,  7, 34, 14,  3, 60, 14, 29, 40,
        0, 62, 37, 38, 71, 71, 22,  2, 99, 39, 45, 91, 99, 82, 48, 80])>

In [ ]:
tf.size(E), E.shape,E.ndim

In [ ]:
# Find the min of a tensor
tf.reduce_min(E)

In [ ]:
# Find the max of a tensor
tf.reduce_max(E)

In [ ]:
# Find the mean
tf.reduce_mean(E)

In [ ]:
# Find the sum
tf.reduce_sum(E)

In [ ]:
# Find the variance
import tensorflow_probability as tfp
tfp.stats.variance(E)

In [ ]:
# Find the standard desviation
tf.math.reduce_std(tf.cast(E,dtype=tf.float32))

## Find the positional maximun and minimun

In [ ]:
# Create a new tensor for finding positional minimun and maximun
tf.random.set_seed(42)
F =tf.random.uniform(shape=[50])
F

In [ ]:
# Finding the positional maximun
tf.argmax(F)

In [ ]:
# Index on our largest value position
F[tf.argmax(F)]

In [ ]:
# Finding the max of F
tf.reduce_max(F)

In [ ]:
# Check for equality
F[tf.argmax(F)] == tf.reduce_max(F)

In [ ]:
tf.argmin(F)

In [ ]:
F[tf.argmin(F)]

In [ ]:
tf.reduce_min(F)

## Squeezing a tensor (removing all single dimensions)

In [ ]:
# Create a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G

In [ ]:
G.shape

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

## One-hot encoding tensors

In [ ]:
# Cretae a list of indices
some_list = [0,1,2,3] #could be red, green, blue, purple

# One hot encode our list of indices
tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

## Squaring, log, square root

In [6]:
# Create a new tensor
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [7]:
# Square
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [8]:
# square root
tf.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [11]:
# log
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

## Tensors and NumPy
Tensorflow interacts beautifully with NumPy arrays

In [13]:
# Create a tensor directly from a NumPy array
J = tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [14]:
# Convert our tensor back to NumPy array
np.array(J) , type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [15]:
# Convert tensor J to a NuPy array
J.numpy(),type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [16]:
J = tf.constant([3.])
J.numpy()[0]

3.0

In [17]:
# The default types of each are slightly different
numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3.,7.,10])
#Check the datatype of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

## Finding access to GPU

In [20]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]